# Examen primer bimestre

In [154]:
import numpy as np
import pandas as pd
import random as ran
from scipy import ndimage
from scipy import misc

 1. Crear un vector de ceros de tamaño 10

In [127]:
vector_ceros = np.zeros(10)
vector_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [144]:
vector_ceros[5] = 1
vector_ceros

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [151]:
vector_cincuenta = np.arange(50)

vector_cincuenta_final = vector_cincuenta[::-1]
print(vector_cincuenta)
print(vector_cincuenta_final)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Crear una matriz de 3 x 3 con valores del cero al 8

In [129]:
matriz_tres_tres = np.arange(9).reshape(3,3)
matriz_tres_tres

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Encontrar los indices que no sean cero en un arreglo

In [153]:
arreglo = np.array([1,2,0,0,4,0])
ceros = arreglo!=0
print(arreglo[ceros])

[1 2 4]


Crear una matriz de identidad 3 x 3

In [131]:
matriz_identidad = np.identity(3)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Crear una matriz 3 x 3 x 3 con valores randomicos

In [132]:
matriz_randomicos=np.random.randint(0,10,27).reshape(3,3,3)
matriz_randomicos

array([[[0, 1, 1],
        [2, 3, 1],
        [3, 2, 8]],

       [[4, 3, 3],
        [3, 9, 2],
        [8, 1, 3]],

       [[9, 5, 8],
        [5, 1, 3],
        [6, 8, 2]]])

Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [133]:
matriz_diez_diez = np.arange(100).reshape(10,10)
matriz_diez_diez

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [134]:
print('maximo:',matriz_diez_diez.max())
print('maximo:',matriz_diez_diez.min())

maximo: 99
maximo: 0


Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [175]:
mapache = misc.face()
mapache
no_repetidos = []
for i in mapache:
    for x in i:
        if x in no_repetidos:
            continue
        else:
            no_repetidos.append(x)
print(no_repetidos)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

¿Como crear una serie de una lista, diccionario o arreglo?

In [135]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

TypeError: 'numpy.ndarray' object is not callable

In [136]:
serie_lista = pd.Series(mylist)
serie_lista

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [137]:
serie_arreglo = pd.Series(myarr)
serie_arreglo

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32

In [138]:
serie_diccionario = pd.Series(mydict)
serie_diccionario

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

¿Como convertir el indice de una serie en una columna de un DataFrame?

In [139]:
ser = pd.Series(mydict) 
df = pd.DataFrame(ser,
                  columns=['Numero'])
# Transformar la serie en dataframe y hacer una columna indice
df

Numero
a       0
b       1
c       2
e       3
d       4
f       5
g       6
h       7
i       8
j       9
k      10
l      11
m      12
n      13
o      14
p      15
q      16
r      17
s      18
t      19
u      20
v      21
w      22
x      23
y      24
z      25